# Domains
main:
  - changed-files:
      - any-glob-to-any-file:
          - src/main/**/*

renderer:
  - changed-files:
      - any-glob-to-any-file:
          - src/renderer/**/*

docs:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**/*

test:
  - changed-files:
      - any-glob-to-any-file:
          - tests/**/*
