# Domains
main:
  - changed-files:
      - src/main/**/*

renderer:
  - changed-files:
      - src/renderer/**/*

docs:
  - changed-files:
      - docs/**/*

test:
  - changed-files:
      - tests/**/*
